# Generated by Django 5.0.4 on 2024-04-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('mob', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
