# Generated by Django 5.0.4 on 2024-05-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('product_image', models.ImageField(upload_to='media')),
                ('category', models.CharField(blank=True, choices=[('Men', 'men'), ('Women', 'women'), ('Kids', 'kids'), ('Best', 'best')], max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
